appConfig:
  theme: neomorphic
  language: en
  layout: horizontal
  iconSize: small
  customColors:
    neomorphic:
      primary: '#fff'
      background: '#060913'
      background-darker: '#12103c'
pageInfo:
  title: Dashy
  description: ''
  navLinks: []
  footerText: ''
sections:
  - name: Social
    items:
      - &ref_0
        title: Facebook
        icon: https://www.facebook.com/favicon.ico
        url: https://www.facebook.com
        target: sametab
        id: 0_603_facebook
      - &ref_1
        title: Twitter
        icon: https://abs.twimg.com/favicons/twitter.3.ico
        url: https://twitter.com
        target: sametab
        id: 1_603_twitter
      - &ref_2
        title: Messenger
        icon: https://static.xx.fbcdn.net/rsrc.php/ym/r/YQbyhl59TWY.ico
        url: https://www.messenger.com/
        target: sametab
        id: 2_603_messenger
      - &ref_3
        title: Reddit
        icon: https://www.reddit.com/favicon.ico
        url: https://www.reddit.com
        target: sametab
        id: 3_603_reddit
      - &ref_4
        title: Mastodon
        icon: >-
          https://cdn.fosstodon.org/site_uploads/files/000/000/007/48/91cda647d1c18689.png
        url: https://fosstodon.org
        target: sametab
        id: 4_603_mastodon
      - &ref_5
        title: Whatsapp
        icon: https://static.whatsapp.net/rsrc.php/v3/yk/r/XLL-1_89W40.png
        url: https://web.whatsapp.com/
        id: 5_603_whatsapp
      - &ref_6
        title: BlueSky
        icon: https://staging.bsky.app/static/favicon-32x32.png
        url: https://staging.bsky.app
        target: sametab
        id: 6_603_bluesky
      - &ref_7
        title: Instagram
        icon: https://static.cdninstagram.com/rsrc.php/y4/r/QaBlI0OZiks.ico
        url: https://www.instagram.com/
        target: sametab
        id: 7_603_instagram
      - &ref_8
        title: LinkedIn
        icon: https://static.licdn.com/aero-v1/sc/h/3loy7tajf3n0cho89wgg0fjre
        url: https://www.linkedin.com/
        target: sametab
        id: 8_603_linkedin
      - &ref_9
        title: Threads
        icon: https://static.cdninstagram.com/rsrc.php/ye/r/lEu8iVizmNW.ico
        url: https://www.threads.net/
        target: sametab
        id: 9_603_threads
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    filteredItems:
      - *ref_0
      - *ref_1
      - *ref_2
      - *ref_3
      - *ref_4
      - *ref_5
      - *ref_6
      - *ref_7
      - *ref_8
      - *ref_9
  - name: Media
    items:
      - &ref_10
        title: Youtube
        icon: https://www.youtube.com/s/desktop/6ca9d352/img/favicon.ico
        url: https://www.youtube.com
        target: sametab
        id: 0_480_youtube
      - &ref_11
        title: Netflix
        icon: https://www.netflix.com/favicon.ico
        url: https://www.netflix.com
        target: sametab
        id: 1_480_netflix
      - &ref_12
        title: Google Photos
        icon: https://photos.google.com/favicon.ico
        url: https://photos.google.com
        target: sametab
        id: 2_480_googlephotos
      - &ref_13
        title: Audiobookshelf
        icon: https://audiobookshelf.tymscar.com/favicon.ico
        url: https://audiobookshelf.tymscar.com/
        target: sametab
        id: 3_480_audiobookshelf
      - &ref_14
        title: Kongregate
        icon: https://www.kongregate.com/favicon.ico
        url: https://www.kongregate.com/
        target: sametab
        id: 4_480_kongregate
      - &ref_15
        title: Twitch
        icon: >-
          https://static.twitchcdn.net/assets/favicon-32-e29e246c157142c94346.png
        url: https://www.twitch.tv/
        target: sametab
        id: 5_480_twitch
      - &ref_16
        title: BBC
        icon: >-
          https://static.files.bbci.co.uk/core/website/assets/static/icons/favicon/bbc/favicon-32.d0dcfb7dcc9c19f549e9.png
        url: https://www.bbc.co.uk/
        target: sametab
        id: 6_480_bbc
      - &ref_17
        title: AOC
        icon: https://adventofcode.com/favicon.png
        url: https://adventofcode.com/
        target: sametab
        id: 7_480_aoc
      - &ref_18
        title: Sunshine
        icon: https://sunshine.tymscar.com/images/sunshine.ico
        url: https://sunshine.tymscar.com
        target: sametab
        id: 8_480_sunshine
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    filteredItems:
      - *ref_10
      - *ref_11
      - *ref_12
      - *ref_13
      - *ref_14
      - *ref_15
      - *ref_16
      - *ref_17
      - *ref_18
  - name: Utilities
    items:
      - &ref_19
        title: Gmail
        icon: https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico
        url: https://mail.google.com
        target: sametab
        id: 0_956_gmail
      - &ref_20
        title: ProtonMail
        icon: https://mail.proton.me/assets/favicon.ico
        url: https://mail.proton.me
        target: sametab
        id: 1_956_protonmail
      - &ref_21
        title: ChatGPT
        icon: https://chat.openai.com/favicon.ico
        url: https://chat.openai.com/chat?model=gpt-4
        target: sametab
        id: 2_956_chatgpt
      - &ref_22
        title: Github
        icon: https://github.githubassets.com/favicons/favicon-dark.png
        url: https://github.com
        target: sametab
        id: 3_956_github
      - &ref_23
        title: Amazon
        icon: https://www.amazon.co.uk/favicon.ico
        url: https://www.amazon.co.uk/
        target: sametab
        id: 4_956_amazon
      - &ref_24
        title: Ebay
        icon: https://www.ebay.co.uk/favicon.ico
        url: https://www.ebay.co.uk
        target: sametab
        id: 5_956_ebay
      - &ref_25
        title: Nix search
        icon: https://search.nixos.org/favicon.png
        url: https://search.nixos.org/
        target: sametab
        id: 6_956_nixsearch
      - &ref_26
        title: Kagi
        icon: https://assets.kagi.com/v2/favicon-32x32.png
        url: https://kagi.com/
        target: sametab
        id: 7_956_kagi
      - &ref_27
        title: Melpa
        icon: https://melpa.org/favicon.ico
        url: https://melpa.org/
        target: sametab
        id: 8_956_melpa
      - &ref_28
        title: Perplexity
        icon: https://framerusercontent.com/images/pta2kExQjjj4WH50JAVR6D1QNFQ.png
        url: https://www.perplexity.ai/
        target: sametab
        id: 9_956_perplexity
      - &ref_29
        title: Open WebUI
        icon: https://ai.tymscar.com/static/favicon.png
        url: https://ai.tymscar.com/
        target: sametab
        id: 10_956_openwebui
      - &ref_30
        title: Claude
        icon: https://claude.ai/favicon.ico
        url: https://claude.ai/new
        target: sametab
        id: 11_956_claude
      - &ref_31
        title: ComfyUI
        icon: https://framerusercontent.com/images/ZdBbq96uSdSV7csYpT0JsoE4.png
        url: https://comfyui.tymscar.com/
        target: sametab
        id: 12_956_comfyui
      - &ref_32
        title: N8n
        icon: https://n8n.io/favicon.ico
        url: https://n8n.tymscar.com/
        target: sametab
        id: 13_956_nn
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    filteredItems:
      - *ref_19
      - *ref_20
      - *ref_21
      - *ref_22
      - *ref_23
      - *ref_24
      - *ref_25
      - *ref_26
      - *ref_27
      - *ref_28
      - *ref_29
      - *ref_30
      - *ref_31
      - *ref_32
  - name: Management
    items:
      - &ref_33
        title: Pihole
        icon: https://docs.pi-hole.net/images/favicon.ico
        url: https://pihole.tymscar.com/
        target: sametab
        id: 0_1021_pihole
      - &ref_34
        title: Home assistant
        icon: https://has.tymscar.com/static/icons/favicon.ico
        url: https://has.tymscar.com/
        target: sametab
        id: 1_1021_homeassistant
      - &ref_35
        title: Synology
        icon: https://www.synology.com/img/icon/favicon@2x.png
        url: https://nas.tymscar.com/
        target: sametab
        id: 2_1021_synology
      - &ref_36
        title: Traefik
        icon: >-
          https://doc.traefik.io/traefik/assets/images/logo-traefik-proxy-icon.svg
        url: https://traefik.tymscar.com/
        target: sametab
        id: 3_1021_traefik
      - &ref_37
        title: Paste
        icon: https://microbin.eu/img/favicon.ico
        url: https://paste.tymscar.com/
        target: sametab
        id: 4_1021_paste
      - &ref_38
        title: Changedetection
        icon: https://changedetection.tymscar.com/static/favicons/favicon.ico
        url: https://changedetection.tymscar.com/
        target: sametab
        id: 5_1021_changedetection
      - &ref_39
        title: Uptime Kuma
        icon: https://kuma.tymscar.com/favicon.ico
        url: https://kuma.tymscar.com
        target: sametab
        id: 6_1021_uptimekuma
      - &ref_40
        title: Unifi
        icon: https://udm.tymscar.com/favicon.ico
        url: https://udm.tymscar.com/
        target: sametab
        id: 7_1021_unifi
      - &ref_41
        title: JetKVM
        icon: https://jetkvm.tymscar.com/static/favicon.png
        url: https://jetkvm.tymscar.com/
        target: sametab
        id: 8_1021_jetkvm
      - &ref_42
        title: LibreCounter
        icon: https://librecounter.tymscar.com/favicon.png
        url: https://librecounter.tymscar.com/
        target: sametab
        id: 9_1021_librecounter
      - &ref_43
        title: TrueNAS
        icon: https://truenas.tymscar.com/ui/assets/images/truenas_ondark_favicon.png
        url: https://truenas.tymscar.com/
        target: sametab
        id: 10_1021_truenas
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    filteredItems:
      - *ref_33
      - *ref_34
      - *ref_35
      - *ref_36
      - *ref_37
      - *ref_38
      - *ref_39
      - *ref_40
      - *ref_41
      - *ref_42
      - *ref_43
